### ISSUE TITLE
Workflow failing with permission error

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-plugin-template-repository#1]
Just got this error:
```
remote: Permission to simonw/datasette-paste-table.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/simonw/datasette-paste-table/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by simonw** [comment]
That fixed it.
